version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/elitedom-store/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Africa/Cairo"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"

  - package-ecosystem: "pip"
    directory: "/elitedom-store/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:15"
      timezone: "Africa/Cairo"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "Africa/Cairo"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
