{
    "name": "Elitedom Store Connector",
    "summary": "Reliable signed catalogue, inventory, and order webhooks for FastAPI",
    "version": "17.0.2.0.0",
    "category": "Sales/Technical",
    "author": "Elitedom",
    "website": "https://elitedom.store",
    "license": "LGPL-3",
    "depends": [
        "base",
        "product",
        "sale_management",
        "sale_stock",
        "stock",
        "delivery",
    ],
    "external_dependencies": {"python": ["requests"]},
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "views/res_config_settings_views.xml",
        "views/product_template_views.xml",
        "views/webhook_outbox_views.xml",
    ],
    "application": False,
    "installable": True,
}
